theme: jekyll-theme-architect
# Site settings
title: "Willis's blog"
description: "Hello everybody"
baseurl: ""
url: "http://songkv5.github.io"

# Build settings
markdown: redcarpet
permalink: pretty
highlighter: pygments
paginate: 3
