# Site settings
title: 凯 の 博客
email: willissong.7@gmail.com 
description: 子曾经曰过：学而时习之，不亦说乎~ # Write an awesome description for your new site here. You can edit this  line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://songkv5.github.io" # the base hostname & protocol for your site
twitter_username: willissong
github_username:  songkv5

# Build settings
markdown: redcarpet:
    extensions: [ "hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify","no_intra_emphasis"]
copyright: 版权声明：本文为willis原创文章， 转载请注明出处, 转载请注明出处 ！